2020-10-14 09:40:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:40:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:40:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:40:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:40:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:40:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:41:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.NAME, USERS.PHONE, USERS.EMAIL, USERS.LAST_EDITED FROM USERS [42102-196]
2020-10-14 09:45:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:45:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:49:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:49:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:49:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:49:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:49:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:49:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:54:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:54:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:54:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:54:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:54:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:54:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:57:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:57:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:57:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:57:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:57:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-14 09:57:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
INSERT INTO USERS (EMAIL, LAST_EDITED, NAME, PHONE) VALUES (?, ?, ?, ?) [42102-196]
2020-10-18 00:49:07 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/abrahamlay/IdeaProjects/BotolPlastikBaru/data/test.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.abraham.service.DatabaseHelper.hikari(DatabaseHelper.kt:55)
	at com.abraham.service.DatabaseHelper.init(DatabaseHelper.kt:24)
	at com.abraham.ApplicationKt$module$1.invoke(Application.kt:30)
	at com.abraham.ApplicationKt$module$1.invoke(Application.kt)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:281)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:125)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:245)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:146)
	at com.abraham.ApplicationKt.module(Application.kt:38)
	at com.abraham.ApplicationTest$testRoot$1.invoke(ApplicationTest.kt:19)
	at com.abraham.ApplicationTest$testRoot$1.invoke(ApplicationTest.kt:16)
	at io.ktor.server.testing.TestEngineKt$withTestApplication$1.invoke(TestEngine.kt:67)
	at io.ktor.server.testing.TestEngineKt$withTestApplication$1.invoke(TestEngine.kt)
	at io.ktor.server.testing.TestEngineKt.withApplication(TestEngine.kt:49)
	at io.ktor.server.testing.TestEngineKt.withApplication$default(TestEngine.kt:43)
	at io.ktor.server.testing.TestEngineKt.withTestApplication(TestEngine.kt:66)
	at com.abraham.ApplicationTest.testRoot(ApplicationTest.kt:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/abrahamlay/IdeaProjects/BotolPlastikBaru/data/test.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 92 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/abrahamlay/IdeaProjects/BotolPlastikBaru/data/test.mv.db [1.4.196/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 87 more
2020-10-18 02:54:10 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/abrahamlay/IdeaProjects/BotolPlastikBaru/data/test.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.abraham.service.DatabaseHelper.hikari(DatabaseHelper.kt:57)
	at com.abraham.service.DatabaseHelper.init(DatabaseHelper.kt:26)
	at com.abraham.ApplicationKt.module(Application.kt:31)
	at com.abraham.ApplicationTest$testRoot$1.invoke(ApplicationTest.kt:23)
	at com.abraham.ApplicationTest$testRoot$1.invoke(ApplicationTest.kt:20)
	at io.ktor.server.testing.TestEngineKt$withTestApplication$1.invoke(TestEngine.kt:67)
	at io.ktor.server.testing.TestEngineKt$withTestApplication$1.invoke(TestEngine.kt)
	at io.ktor.server.testing.TestEngineKt.withApplication(TestEngine.kt:49)
	at io.ktor.server.testing.TestEngineKt.withApplication$default(TestEngine.kt:43)
	at io.ktor.server.testing.TestEngineKt.withTestApplication(TestEngine.kt:66)
	at com.abraham.ApplicationTest.testRoot(ApplicationTest.kt:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/abrahamlay/IdeaProjects/BotolPlastikBaru/data/test.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 86 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/abrahamlay/IdeaProjects/BotolPlastikBaru/data/test.mv.db [1.4.196/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 81 more
2020-10-18 13:33:48 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/abrahamlay/IdeaProjects/BotolPlastikBaru/data/test.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.abraham.service.DatabaseHelper.hikari(DatabaseHelper.kt:57)
	at com.abraham.service.DatabaseHelper.init(DatabaseHelper.kt:26)
	at com.abraham.ApplicationKt.module(Application.kt:29)
	at com.abraham.ApplicationKt.module$default(Application.kt:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:384)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:330)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:275)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:274)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:290)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:272)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:125)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:245)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:146)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:26)
	at com.abraham.MyAppKt.main(MyApp.kt:3)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/abrahamlay/IdeaProjects/BotolPlastikBaru/data/test.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 56 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/abrahamlay/IdeaProjects/BotolPlastikBaru/data/test.mv.db [1.4.196/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 51 more
